// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/errors/async-effect-error": {
    params: {};
  };
  "/errors/event-handler-error": {
    params: {};
  };
  "/errors/fails-ssr": {
    params: {};
  };
  "/errors/hook-rule": {
    params: {};
  };
  "/errors/hydration-mismatch": {
    params: {};
  };
  "/errors/infinite-render-loop": {
    params: {};
  };
  "/errors/json-parse-error": {
    params: {};
  };
  "/errors/localstorage-ssr": {
    params: {};
  };
  "/errors/missing-component": {
    params: {};
  };
  "/errors/null-access": {
    params: {};
  };
  "/errors/render-object": {
    params: {};
  };
  "/errors/stack-overflow": {
    params: {};
  };
  "/errors/type-error-not-function": {
    params: {};
  };
  "/errors/undefined-access": {
    params: {};
  };
  "/errors/unhandled-promise": {
    params: {};
  };
  "/__create/social-dev-shim": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/errors/async-effect-error" | "/errors/event-handler-error" | "/errors/fails-ssr" | "/errors/hook-rule" | "/errors/hydration-mismatch" | "/errors/infinite-render-loop" | "/errors/json-parse-error" | "/errors/localstorage-ssr" | "/errors/missing-component" | "/errors/null-access" | "/errors/render-object" | "/errors/stack-overflow" | "/errors/type-error-not-function" | "/errors/undefined-access" | "/errors/unhandled-promise" | "/__create/social-dev-shim" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./errors/async-effect-error/page.jsx": {
    id: "errors/async-effect-error/page";
    page: "/errors/async-effect-error";
  };
  "./errors/event-handler-error/page.jsx": {
    id: "errors/event-handler-error/page";
    page: "/errors/event-handler-error";
  };
  "./errors/fails-ssr/page.jsx": {
    id: "errors/fails-ssr/page";
    page: "/errors/fails-ssr";
  };
  "./errors/hook-rule/page.jsx": {
    id: "errors/hook-rule/page";
    page: "/errors/hook-rule";
  };
  "./errors/hydration-mismatch/page.jsx": {
    id: "errors/hydration-mismatch/page";
    page: "/errors/hydration-mismatch";
  };
  "./errors/infinite-render-loop/page.jsx": {
    id: "errors/infinite-render-loop/page";
    page: "/errors/infinite-render-loop";
  };
  "./errors/json-parse-error/page.jsx": {
    id: "errors/json-parse-error/page";
    page: "/errors/json-parse-error";
  };
  "./errors/localstorage-ssr/page.jsx": {
    id: "errors/localstorage-ssr/page";
    page: "/errors/localstorage-ssr";
  };
  "./errors/missing-component/page.jsx": {
    id: "errors/missing-component/page";
    page: "/errors/missing-component";
  };
  "./errors/null-access/page.jsx": {
    id: "errors/null-access/page";
    page: "/errors/null-access";
  };
  "./errors/render-object/page.jsx": {
    id: "errors/render-object/page";
    page: "/errors/render-object";
  };
  "./errors/stack-overflow/page.jsx": {
    id: "errors/stack-overflow/page";
    page: "/errors/stack-overflow";
  };
  "./errors/type-error-not-function/page.jsx": {
    id: "errors/type-error-not-function/page";
    page: "/errors/type-error-not-function";
  };
  "./errors/undefined-access/page.jsx": {
    id: "errors/undefined-access/page";
    page: "/errors/undefined-access";
  };
  "./errors/unhandled-promise/page.jsx": {
    id: "errors/unhandled-promise/page";
    page: "/errors/unhandled-promise";
  };
  "./__create/social-dev-shim/page.jsx": {
    id: "__create/social-dev-shim/page";
    page: "/__create/social-dev-shim";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "errors/async-effect-error/page": typeof import("./src/app/./errors/async-effect-error/page.jsx");
  "errors/event-handler-error/page": typeof import("./src/app/./errors/event-handler-error/page.jsx");
  "errors/fails-ssr/page": typeof import("./src/app/./errors/fails-ssr/page.jsx");
  "errors/hook-rule/page": typeof import("./src/app/./errors/hook-rule/page.jsx");
  "errors/hydration-mismatch/page": typeof import("./src/app/./errors/hydration-mismatch/page.jsx");
  "errors/infinite-render-loop/page": typeof import("./src/app/./errors/infinite-render-loop/page.jsx");
  "errors/json-parse-error/page": typeof import("./src/app/./errors/json-parse-error/page.jsx");
  "errors/localstorage-ssr/page": typeof import("./src/app/./errors/localstorage-ssr/page.jsx");
  "errors/missing-component/page": typeof import("./src/app/./errors/missing-component/page.jsx");
  "errors/null-access/page": typeof import("./src/app/./errors/null-access/page.jsx");
  "errors/render-object/page": typeof import("./src/app/./errors/render-object/page.jsx");
  "errors/stack-overflow/page": typeof import("./src/app/./errors/stack-overflow/page.jsx");
  "errors/type-error-not-function/page": typeof import("./src/app/./errors/type-error-not-function/page.jsx");
  "errors/undefined-access/page": typeof import("./src/app/./errors/undefined-access/page.jsx");
  "errors/unhandled-promise/page": typeof import("./src/app/./errors/unhandled-promise/page.jsx");
  "__create/social-dev-shim/page": typeof import("./src/app/./__create/social-dev-shim/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};