blank_issues_enabled: true
contact_links:
  - name: Security report
    url: https://github.com/CDUESTC-OpenAtom-Open-Source-Club/Open-Source-Club-Nav/security/advisories/new
    about: Please report security issues privately.
